# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgbpJl_KDDzvwk4XdhuHn_ZI96n5f5O3
"""

s1 = "hello students! this is real world of python machine learning  "

print("The value of s1 : ",s1)

# it is built in methods and return the string whose first latter of first word is capital

capString = s1.capitalize()

print(capString)

#Title :  it is built in methods and return the string whose first latter of all words is capital

titleString = s1.title()

print(titleString)

