# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8TuIxIZ-cqrIkB9K5QUQetYc2pgVOet
"""

string = "Hello Student"

print(string)

# access the elements using indexex
print(string[2])

try:
  print(string[20])
except IndexError as e:
  print(e)

# Slicing of string
# string([start:step])
print(string[0:len(string)])

# Slicing of string
print(string[2:len(string)])

print(string[0:len(string):3])

# create a string hello python
# print python using index
string = "Hello python"

print(string[-7::1])

print(string[-1:-7:-1])

